[build]
  publish = "public"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-hashfiles"

[plugins.inputs]
  entryPoints = [
    "*.html",
	"*.js",
	"*.css"
  ]

  staticDir = "/public/"